# Generated by Django 5.0.4 on 2024-04-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="address",
            field=models.TextField(max_length=100, null=True),
        ),
    ]
